25/01/22 (15:27:46) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:08:11) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:08:11) | WARNING: No theme named "+catppuccin" found!
26/01/22 (18:08:17) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:10:33) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:12:59) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:13:03) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
