25/01/22 (15:27:46) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:08:11) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:08:11) | WARNING: No theme named "+catppuccin" found!
26/01/22 (18:08:17) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:10:33) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:12:59) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:13:03) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
26/01/22 (18:39:43) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
26/01/22 (18:59:01) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
27/01/22 (09:37:24) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
27/01/22 (10:31:34) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
27/01/22 (10:32:02) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
27/01/22 (15:50:38) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
27/01/22 (15:56:01) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 957, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
28/01/22 (16:02:04) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
28/01/22 (18:09:24) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
28/01/22 (18:37:30) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
29/01/22 (10:14:29) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
29/01/22 (14:06:21) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
29/01/22 (16:20:12) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
30/01/22 (16:01:47) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
30/01/22 (16:06:59) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
30/01/22 (22:32:58) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
31/01/22 (14:37:22) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
31/01/22 (16:08:25) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
01/02/22 (00:07:21) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
01/02/22 (09:06:37) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
01/02/22 (16:48:55) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (11:41:34) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (11:47:37) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (15:05:54) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (15:06:42) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (15:06:44) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (15:07:35) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (15:09:03) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (15:09:03) | WARNING: No theme named "Catppuccin" found!
02/02/22 (15:09:08) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (15:09:27) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
02/02/22 (15:11:30) | ERROR: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/azaan/.config/bpytop/themes'
